[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string] $OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\svg-thorvg-release-evidence')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Reflection.Metadata

$markdownRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $markdownRoot '..')).Path
$runName = 'run-' + [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmssfff', [Globalization.CultureInfo]::InvariantCulture)
$runDirectory = [IO.Path]::GetFullPath((Join-Path $OutputDirectory $runName))
[IO.Directory]::CreateDirectory($runDirectory) | Out-Null
$evidenceLockPath = Join-Path $runDirectory 'evidence.packages.lock.json'

# WindowsAppSDK self-contained targets invoke mt.exe by name. Prefer the pinned
# 26100 SDK host tool when it is installed but was not placed on PATH by the shell.
$sdkTools = 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64'
if (Test-Path -LiteralPath (Join-Path $sdkTools 'mt.exe') -PathType Leaf) {
    $env:PATH = $sdkTools + [IO.Path]::PathSeparator + $env:PATH
}

function Invoke-DotNet {
    param([Parameter(Mandatory)][string[]] $Arguments)

    if ($Arguments[0] -eq 'restore') {
        # The evidence source is disposable. Do not require or rewrite its copied
        # lock files, which may have been generated by a different SDK patch.
        $Arguments += @(
            '-p:RestorePackagesWithLockFile=false',
            '-p:RestoreLockedMode=false',
            ("-p:NuGetLockFilePath=$evidenceLockPath")
        )
    }
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
    }
}

function Get-Sha256 {
    param([Parameter(Mandatory)][string] $Path)

    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Get-StreamSha256 {
    param([Parameter(Mandatory)][IO.Stream] $Stream)

    $hash = [Security.Cryptography.SHA256]::Create()
    try { return [Convert]::ToHexString($hash.ComputeHash($Stream)).ToLowerInvariant() }
    finally { $hash.Dispose() }
}

function Get-PeMachine {
    param([Parameter(Mandatory)][string] $Path)

    $bytes = [IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -lt 64 -or $bytes[0] -ne 0x4d -or $bytes[1] -ne 0x5a) {
        throw "'$Path' is not an MZ executable."
    }
    $peOffset = [BitConverter]::ToInt32($bytes, 0x3c)
    if ($peOffset -lt 0 -or $peOffset + 6 -gt $bytes.Length -or
        $bytes[$peOffset] -ne 0x50 -or $bytes[$peOffset + 1] -ne 0x45) {
        throw "'$Path' has no valid PE signature."
    }
    switch ([BitConverter]::ToUInt16($bytes, $peOffset + 4)) {
        332 { return 'x86' }
        34404 { return 'x64' }
        43620 { return 'arm64' }
        default { return 'unknown' }
    }
}

function Get-ManagedPeEvidence {
    param([Parameter(Mandatory)][string] $Path)

    $stream = [IO.File]::OpenRead($Path)
    $reader = $null
    try {
        $reader = [Reflection.PortableExecutable.PEReader]::new($stream)
        $headers = $reader.PEHeaders
        $corHeader = $headers.CorHeader
        if ($null -eq $corHeader) { throw "'$Path' is not a managed PE." }
        $flags = [int] $corHeader.Flags
        $machine = $headers.CoffHeader.Machine.ToString()
        $magic = $headers.PEHeader.Magic.ToString()
        $ilOnly = ($flags -band 1) -ne 0
        $requires32Bit = ($flags -band 2) -ne 0
        $prefers32Bit = ($flags -band 0x20000) -ne 0
        return [pscustomobject][ordered]@{
            machine = $machine
            peMagic = $magic
            ilOnly = $ilOnly
            requires32Bit = $requires32Bit
            prefers32Bit = $prefers32Bit
            anyCpu = $machine -eq 'I386' -and $magic -eq 'PE32' -and
                $ilOnly -and -not $requires32Bit -and -not $prefers32Bit
        }
    }
    finally {
        if ($null -ne $reader) { $reader.Dispose() }
        else { $stream.Dispose() }
    }
}

function Invoke-CompatibleExecutable {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter(Mandatory)][string] $Rid,
        [Parameter(Mandatory)][string] $HostArchitecture,
        [string[]] $Arguments = @()
    )

    $compatible = $Rid -eq ('win-' + $HostArchitecture) -or
        ($HostArchitecture -eq 'x64' -and $Rid -eq 'win-x86')
    if (-not $compatible) {
        return [pscustomobject][ordered]@{
            executed = $false
            exitCode = $null
            output = $null
            reason = "Cross-published $Rid output cannot run on the $HostArchitecture evidence host."
        }
    }

    $output = @(& $Path @Arguments 2>&1)
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "Deployment smoke '$Path' failed with exit code $exitCode. Output: $($output -join "`n")"
    }
    return [pscustomobject][ordered]@{
        executed = $true
        exitCode = $exitCode
        output = ($output -join "`n")
        reason = $null
    }
}

function Copy-DeploymentWithoutThorVg {
    param(
        [Parameter(Mandatory)][string] $Source,
        [Parameter(Mandatory)][string] $Destination
    )

    [IO.Directory]::CreateDirectory($Destination) | Out-Null
    foreach ($item in Get-ChildItem -LiteralPath $Source -Force) {
        if ($item.Name -ieq 'thorvg.dll') { continue }
        Copy-Item -LiteralPath $item.FullName -Destination $Destination -Recurse
    }
}

$testsProject = Join-Path $markdownRoot 'MarkdownRenderer.Svg.ThorVG.Tests\MarkdownRenderer.Svg.ThorVG.Tests.csproj'
$pixelTestsProject = Join-Path $markdownRoot 'MarkdownRenderer.PixelTests\MarkdownRenderer.PixelTests.csproj'
$packageProjects = @(
    (Join-Path $markdownRoot 'MarkdownRenderer.Core\MarkdownRenderer.Core.csproj'),
    (Join-Path $markdownRoot 'MarkdownRenderer\MarkdownRenderer.csproj'),
    (Join-Path $markdownRoot 'MarkdownRenderer.Package\MarkdownRenderer.Package.csproj'),
    (Join-Path $markdownRoot 'MarkdownRenderer.Svg.ThorVG\MarkdownRenderer.Svg.ThorVG.csproj')
)
$testResultsDirectory = Join-Path $runDirectory 'tests'
$pixelArtifactsDirectory = Join-Path $runDirectory 'pixels'
$isolatedBuildDirectory = Join-Path $runDirectory 'build-artifacts'
$candidatePackages = Join-Path $runDirectory 'packages-candidate'
$referencePackages = Join-Path $runDirectory 'packages-reference'
[IO.Directory]::CreateDirectory($testResultsDirectory) | Out-Null
[IO.Directory]::CreateDirectory($isolatedBuildDirectory) | Out-Null
[IO.Directory]::CreateDirectory($candidatePackages) | Out-Null
[IO.Directory]::CreateDirectory($referencePackages) | Out-Null

Push-Location $repositoryRoot
try {
    Invoke-DotNet @(
        'restore', $testsProject, '-p:Configuration=Release', '-p:Platform=x64',
        '-p:RestoreLockedMode=false', '-p:RestorePackagesWithLockFile=false',
        ('-p:ArtifactsPath=' + $isolatedBuildDirectory), '--disable-parallel'
    )
    Invoke-DotNet @(
        'test', $testsProject, '-c', 'Release', '-p:Platform=x64', '--no-restore',
        '-p:RestorePackagesWithLockFile=false', ('-p:ArtifactsPath=' + $isolatedBuildDirectory),
        '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
        '--logger', 'trx;LogFileName=svg-thorvg-contracts.trx',
        '--results-directory', $testResultsDirectory
    )
    Invoke-DotNet @(
        'restore', $pixelTestsProject, '-p:Configuration=Release', '-p:Platform=x64',
        '-p:RestoreLockedMode=false', '-p:RestorePackagesWithLockFile=false',
        ('-p:ArtifactsPath=' + $isolatedBuildDirectory), '--disable-parallel'
    )
    $previousPixelRoot = [Environment]::GetEnvironmentVariable(
        'MARKDOWN_RENDERER_SVG_ARTIFACT_ROOT',
        [EnvironmentVariableTarget]::Process)
    try {
        [Environment]::SetEnvironmentVariable(
            'MARKDOWN_RENDERER_SVG_ARTIFACT_ROOT',
            $pixelArtifactsDirectory,
            [EnvironmentVariableTarget]::Process)
        Invoke-DotNet @(
            'test', $pixelTestsProject, '-c', 'Release', '-p:Platform=x64', '--no-restore',
            '-p:RestorePackagesWithLockFile=false', ('-p:ArtifactsPath=' + $isolatedBuildDirectory),
            '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
            '--logger', 'trx;LogFileName=svg-pixels.trx',
            '--results-directory', $testResultsDirectory
        )
    }
    finally {
        [Environment]::SetEnvironmentVariable(
            'MARKDOWN_RENDERER_SVG_ARTIFACT_ROOT',
            $previousPixelRoot,
            [EnvironmentVariableTarget]::Process)
    }
    foreach ($project in $packageProjects) {
        Invoke-DotNet @(
            'restore', $project, '-p:Configuration=Release', '-p:Platform=x64',
            '-p:RestoreLockedMode=false', '-p:RestorePackagesWithLockFile=false',
            ('-p:ArtifactsPath=' + $isolatedBuildDirectory), '--disable-parallel'
        )
        foreach ($directory in @($candidatePackages, $referencePackages)) {
            Invoke-DotNet @(
                'pack', $project, '-c', 'Release', '-p:Platform=x64', '--no-restore',
                '-p:RestorePackagesWithLockFile=false', ('-p:ArtifactsPath=' + $isolatedBuildDirectory),
                '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
                '-o', $directory
            )
        }
    }
}
finally {
    Pop-Location
}

$trx = [xml] (Get-Content -LiteralPath (Join-Path $testResultsDirectory 'svg-thorvg-contracts.trx') -Raw)
$counters = $trx.TestRun.ResultSummary.Counters
if ([int] $counters.failed -ne 0 -or [int] $counters.executed -ne [int] $counters.passed) {
    throw 'ThorVG contract-test evidence contains a failure or non-passing executed test.'
}
$pixelTrx = [xml] (Get-Content -LiteralPath (Join-Path $testResultsDirectory 'svg-pixels.trx') -Raw)
$pixelCounters = $pixelTrx.TestRun.ResultSummary.Counters
if ([int] $pixelCounters.failed -ne 0 -or
    [int] $pixelCounters.executed -ne [int] $pixelCounters.passed) {
    throw 'ThorVG SVG pixel evidence contains a failure or non-passing executed test.'
}

& (Join-Path $PSScriptRoot 'Normalize-NuGetPackageArchives.ps1') -PackageDirectory $candidatePackages
& (Join-Path $PSScriptRoot 'Normalize-NuGetPackageArchives.ps1') -PackageDirectory $referencePackages
$referenceManifest = Join-Path $runDirectory 'package-reproducibility-reference.json'
& (Join-Path $PSScriptRoot 'New-PackageReproducibilityManifest.ps1') `
    -PackageDirectory $referencePackages `
    -OutputPath $referenceManifest
$complianceDirectory = Join-Path $runDirectory 'package-compliance'
& (Join-Path $PSScriptRoot 'Invoke-PackageCompliance.ps1') `
    -PackageDirectory $candidatePackages `
    -OutputDirectory $complianceDirectory `
    -ReferenceManifest $referenceManifest `
    -FailOnUnknownLicense `
    -SkipSizeGates

$package = Get-ChildItem -LiteralPath $candidatePackages -Filter 'MarkdownRenderer.Svg.ThorVG.*.nupkg' -File |
    Where-Object { $_.Name -notlike '*.symbols.nupkg' } |
    Select-Object -First 1
if ($null -eq $package) { throw 'The ThorVG package was not produced.' }

$provenance = Get-Content -LiteralPath (Join-Path $markdownRoot 'MarkdownRenderer.Svg.ThorVG\THORVG_PROVENANCE.json') -Raw |
    ConvertFrom-Json
$provenanceByPath = @{}
foreach ($asset in @($provenance.assets)) { $provenanceByPath[[string] $asset.path] = $asset }
$requiredEntries = @(
    'LICENSE',
    'README.md',
    'THIRD-PARTY-NOTICES.md',
    'THORVG_LICENSE',
    'THORVG_PROVENANCE.json',
    'lib/net10.0-windows10.0.26100/MarkdownRenderer.Svg.ThorVG.dll',
    'lib/net10.0-windows10.0.26100/MarkdownRenderer.Svg.ThorVG.xml',
    'runtimes/win-x86/native/thorvg.dll',
    'runtimes/win-x64/native/thorvg.dll',
    'runtimes/win-arm64/native/thorvg.dll'
)
$nativeCapBytes = [long] (400KB)
$nativeAssets = [Collections.Generic.List[object]]::new()
$managedLibraryPath = Join-Path $runDirectory 'MarkdownRenderer.Svg.ThorVG.pack.dll'
$archive = [IO.Compression.ZipFile]::OpenRead($package.FullName)
try {
    $entryNames = @($archive.Entries.FullName)
    foreach ($required in $requiredEntries) {
        if ($required -notin $entryNames) { throw "ThorVG package is missing '$required'." }
    }
    $nativeEntries = @($archive.Entries | Where-Object {
        $_.FullName -match '^runtimes/win-(x86|x64|arm64)/native/thorvg\.dll$'
    })
    if ($nativeEntries.Count -ne 3) {
        throw 'ThorVG must package exactly one native DLL for x86, x64, and ARM64.'
    }
    foreach ($entry in $nativeEntries) {
        if ($entry.CompressedLength -gt $nativeCapBytes) {
            throw "Selected-RID asset '$($entry.FullName)' exceeds the 400 KiB compressed cap."
        }
        $expected = $provenanceByPath[$entry.FullName]
        if ($null -eq $expected) { throw "No provenance record exists for '$($entry.FullName)'." }
        $stream = $entry.Open()
        try { $sha256 = Get-StreamSha256 -Stream $stream } finally { $stream.Dispose() }
        if ($entry.Length -ne [long] $expected.bytes -or $sha256 -ne [string] $expected.sha256) {
            throw "Packaged asset '$($entry.FullName)' differs from its pinned provenance."
        }
        $nativeAssets.Add([pscustomobject][ordered]@{
            path = $entry.FullName
            peMachine = [string] $expected.peMachine
            uncompressedBytes = $entry.Length
            compressedBytes = $entry.CompressedLength
            capBytes = $nativeCapBytes
            headroomBytes = $nativeCapBytes - $entry.CompressedLength
            sha256 = $sha256
        })
    }
    $managedEntry = $archive.GetEntry('lib/net10.0-windows10.0.26100/MarkdownRenderer.Svg.ThorVG.dll')
    $managedStream = $managedEntry.Open()
    $managedFile = [IO.File]::Create($managedLibraryPath)
    try { $managedStream.CopyTo($managedFile) }
    finally { $managedFile.Dispose(); $managedStream.Dispose() }

    $nuspecEntry = $archive.GetEntry('MarkdownRenderer.Svg.ThorVG.nuspec')
    $reader = [IO.StreamReader]::new($nuspecEntry.Open())
    try { $nuspec = [xml] $reader.ReadToEnd() } finally { $reader.Dispose() }
    $packageVersion = [string] $nuspec.package.metadata.version
}
finally {
    $archive.Dispose()
}

$managedPe = Get-ManagedPeEvidence -Path $managedLibraryPath
if (-not $managedPe.anyCpu) { throw 'The managed ThorVG facade is not AnyCPU IL.' }

$leanPackageEvidence = [Collections.Generic.List[object]]::new()
foreach ($pattern in @('MarkdownRenderer.Core.*.nupkg', 'MarkdownRenderer.WinUI.*.nupkg', 'MarkdownRenderer.1.*.nupkg')) {
    $leanPackage = Get-ChildItem -LiteralPath $candidatePackages -Filter $pattern -File |
        Where-Object { $_.Name -notlike '*.symbols.nupkg' } | Select-Object -First 1
    if ($null -eq $leanPackage) { throw "Expected lean package '$pattern' was not produced." }
    $leanArchive = [IO.Compression.ZipFile]::OpenRead($leanPackage.FullName)
    try {
        $nativeCount = @($leanArchive.Entries | Where-Object { $_.FullName -match '(?i)^runtimes/.+/native/' }).Count
        if ($nativeCount -ne 0) { throw "Lean package '$($leanPackage.Name)' contains native bytes." }
        $leanPackageEvidence.Add([pscustomobject][ordered]@{
            package = $leanPackage.Name
            compressedBytes = $leanPackage.Length
            nativeAssetCount = $nativeCount
        })
    }
    finally { $leanArchive.Dispose() }
}

$consumerDirectory = Join-Path $runDirectory 'package-consumer'
[IO.Directory]::CreateDirectory($consumerDirectory) | Out-Null
$consumerProject = @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU' or '$(Platform)' == 'Any CPU'">x64</Platform>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Windows SDK projection assemblies currently emit aggregate IL2104
         warnings under full trim. Keep compiler/analyzer warnings fatal while
         allowing the platform-owned projection warnings to remain diagnostic. -->
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
    <UseWinUI>false</UseWinUI>
    <WindowsAppSdkSelfContained>true</WindowsAppSdkSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <!-- Restore NativeAOT targeting packs up front. The trimmed/single-file
         lane explicitly overrides this property at publish time. -->
    <PublishAot>true</PublishAot>
    <RestoreLockedMode>false</RestoreLockedMode>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <!-- Keep restored package content outside the project tree. WinUI's XAML
         item discovery must never treat dependency-provided generic.xaml or
         MSIX property-page XAML as application pages. -->
    <RestorePackagesPath>$(MSBuildProjectDirectory)\..\consumer-packages-cache</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownRenderer.Svg.ThorVG" Version="__VERSION__" />
  </ItemGroup>
</Project>
'@.Replace('__VERSION__', $packageVersion)
[IO.File]::WriteAllText(
    (Join-Path $consumerDirectory 'SvgThorVgPackageConsumer.csproj'),
    $consumerProject,
    [Text.UTF8Encoding]::new($false))
[IO.File]::Copy(
    (Join-Path $markdownRoot 'MarkdownRenderer.Svg.ThorVG.AotSmoke\Program.cs'),
    (Join-Path $consumerDirectory 'Program.cs'))
$consumerProjectPath = Join-Path $consumerDirectory 'SvgThorVgPackageConsumer.csproj'

Push-Location $repositoryRoot
try {
    Invoke-DotNet @(
        'restore', $consumerProjectPath, '-p:Configuration=Release',
        '-p:RestoreLockedMode=false', ('-p:RestoreAdditionalProjectSources=' + $candidatePackages),
        '--no-cache', '--disable-parallel'
    )
}
finally { Pop-Location }

$hostArchitecture = [Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$matrix = @(
    [pscustomobject]@{ Platform = 'x86'; Rid = 'win-x86'; Machine = 'x86' },
    [pscustomobject]@{ Platform = 'x64'; Rid = 'win-x64'; Machine = 'x64' },
    [pscustomobject]@{ Platform = 'ARM64'; Rid = 'win-arm64'; Machine = 'arm64' }
)
$deployments = [Collections.Generic.List[object]]::new()
foreach ($target in $matrix) {
    foreach ($mode in @('nativeaot', 'trimmed-single-file')) {
        $publishDirectory = Join-Path $runDirectory ($mode + '-' + $target.Rid)
        $arguments = @(
            'publish', $consumerProjectPath, '-c', 'Release', '-r', $target.Rid,
            ('-p:Platform=' + $target.Platform), '--self-contained', 'true', '--no-restore',
            '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false', '-o', $publishDirectory
        )
        if ($mode -eq 'nativeaot') {
            $arguments += @('-p:PublishAot=true', '-p:PublishTrimmed=true', '-p:TrimMode=full')
        }
        else {
            $arguments += @(
                '-p:PublishAot=false', '-p:PublishTrimmed=true', '-p:TrimMode=full',
                '-p:PublishSingleFile=true'
            )
        }
        Push-Location $repositoryRoot
        try { Invoke-DotNet $arguments } finally { Pop-Location }

        $executable = Join-Path $publishDirectory 'SvgThorVgPackageConsumer.exe'
        $nativeLibrary = Join-Path $publishDirectory 'thorvg.dll'
        $nativeDisposition = 'adjacent'
        if (-not (Test-Path -LiteralPath $nativeLibrary -PathType Leaf) -and
            $mode -eq 'trimmed-single-file') {
            # WindowsAppSDK's single-file target embeds native libraries for
            # extraction. Validate the exact RID-selected input that entered
            # the bundle; executing compatible outputs below proves extraction.
            $nativeLibrary = Join-Path $consumerDirectory (
                'bin\' + $target.Platform + '\Release\net10.0-windows10.0.26100.0\' +
                $target.Rid + '\thorvg.dll')
            $nativeDisposition = 'embedded-for-extraction'
        }
        if (-not (Test-Path -LiteralPath $executable -PathType Leaf) -or
            -not (Test-Path -LiteralPath $nativeLibrary -PathType Leaf)) {
            throw "$mode $($target.Rid) did not produce an executable and selected ThorVG runtime input."
        }
        $executableMachine = Get-PeMachine $executable
        $nativeMachine = Get-PeMachine $nativeLibrary
        if ($executableMachine -ne $target.Machine -or $nativeMachine -ne $target.Machine) {
            throw "$mode $($target.Rid) produced $executableMachine/$nativeMachine; expected $($target.Machine)."
        }
        $extraNativeAssets = @(Get-ChildItem -LiteralPath $publishDirectory -Recurse -Filter 'thorvg.dll' -File)
        $expectedPublishedAssets = if ($nativeDisposition -eq 'adjacent') { 1 } else { 0 }
        if ($extraNativeAssets.Count -ne $expectedPublishedAssets) {
            throw "$mode $($target.Rid) published $($extraNativeAssets.Count) adjacent ThorVG assets; expected $expectedPublishedAssets."
        }
        $execution = Invoke-CompatibleExecutable `
            -Path $executable -Rid $target.Rid -HostArchitecture $hostArchitecture
        $deployments.Add([pscustomobject][ordered]@{
            mode = $mode
            rid = $target.Rid
            executableMachine = $executableMachine
            nativeMachine = $nativeMachine
            selectedNativeAssetCount = 1
            publishedAdjacentNativeAssetCount = $extraNativeAssets.Count
            nativeDisposition = $nativeDisposition
            executableBytes = (Get-Item -LiteralPath $executable).Length
            nativeBytes = (Get-Item -LiteralPath $nativeLibrary).Length
            nativeSha256 = Get-Sha256 $nativeLibrary
            executed = $execution.executed
            exitCode = $execution.exitCode
            output = $execution.output
            skipReason = $execution.reason
        })
    }
}

$fallbacks = [Collections.Generic.List[object]]::new()
$x64Deployment = Join-Path $runDirectory 'nativeaot-win-x64'
$missingDeployment = Join-Path $runDirectory 'fallback-missing-native'
Copy-DeploymentWithoutThorVg -Source $x64Deployment -Destination $missingDeployment
$missingExecution = Invoke-CompatibleExecutable `
    -Path (Join-Path $missingDeployment 'SvgThorVgPackageConsumer.exe') `
    -Rid 'win-x64' -HostArchitecture $hostArchitecture `
    -Arguments @('--expect-unavailable')
$fallbacks.Add([pscustomobject][ordered]@{
    scenario = 'missing-native'
    executed = $missingExecution.executed
    exitCode = $missingExecution.exitCode
    output = $missingExecution.output
})

$wrongDeployment = Join-Path $runDirectory 'fallback-wrong-architecture'
Copy-DeploymentWithoutThorVg -Source $x64Deployment -Destination $wrongDeployment
[IO.File]::Copy(
    (Join-Path $markdownRoot 'MarkdownRenderer\native\win-arm64\thorvg.dll'),
    (Join-Path $wrongDeployment 'thorvg.dll'))
$wrongExecution = Invoke-CompatibleExecutable `
    -Path (Join-Path $wrongDeployment 'SvgThorVgPackageConsumer.exe') `
    -Rid 'win-x64' -HostArchitecture $hostArchitecture `
    -Arguments @('--expect-unavailable')
$fallbacks.Add([pscustomobject][ordered]@{
    scenario = 'wrong-architecture'
    injectedMachine = Get-PeMachine (Join-Path $wrongDeployment 'thorvg.dll')
    executed = $wrongExecution.executed
    exitCode = $wrongExecution.exitCode
    output = $wrongExecution.output
})

$report = [pscustomobject][ordered]@{
    schemaVersion = 1
    generatedUtc = [DateTime]::UtcNow.ToString('O', [Globalization.CultureInfo]::InvariantCulture)
    hostArchitecture = $hostArchitecture
    contractTests = [pscustomobject][ordered]@{
        total = [int] $counters.total
        executed = [int] $counters.executed
        passed = [int] $counters.passed
        failed = [int] $counters.failed
        trx = (Join-Path $testResultsDirectory 'svg-thorvg-contracts.trx')
    }
    pixelTests = [pscustomobject][ordered]@{
        total = [int] $pixelCounters.total
        executed = [int] $pixelCounters.executed
        passed = [int] $pixelCounters.passed
        failed = [int] $pixelCounters.failed
        trx = (Join-Path $testResultsDirectory 'svg-pixels.trx')
        artifactDirectory = $pixelArtifactsDirectory
    }
    package = [pscustomobject][ordered]@{
        id = 'MarkdownRenderer.Svg.ThorVG'
        version = $packageVersion
        path = $package.FullName
        compressedBytes = $package.Length
        sha256 = Get-Sha256 $package.FullName
        nativeCapBytes = $nativeCapBytes
        selectedRidNativeAssets = @($nativeAssets)
        managedFacade = $managedPe
    }
    leanPackages = @($leanPackageEvidence)
    compliance = [pscustomobject][ordered]@{
        directory = $complianceDirectory
        nativeAbi = (Join-Path $complianceDirectory 'native-package-compliance.json')
        reproducibility = (Join-Path $complianceDirectory 'package-reproducibility.json')
        referenceReproducibility = $referenceManifest
    }
    deployments = @($deployments)
    failureFallbacks = @($fallbacks)
}
$reportPath = Join-Path $runDirectory 'svg-thorvg-release-evidence.json'
[IO.File]::WriteAllText(
    $reportPath,
    ($report | ConvertTo-Json -Depth 20) + "`n",
    [Text.UTF8Encoding]::new($false))

Write-Host "ThorVG release gates passed. Evidence: '$reportPath'."
