[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string] $OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\math-release-evidence')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.IO.Compression.FileSystem

$markdownRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $markdownRoot '..')).Path
$runName = 'run-' + [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmssfff', [Globalization.CultureInfo]::InvariantCulture)
$runDirectory = [IO.Path]::GetFullPath((Join-Path $OutputDirectory $runName))
[IO.Directory]::CreateDirectory($runDirectory) | Out-Null
$evidenceLockPath = Join-Path $runDirectory 'evidence.packages.lock.json'

function Invoke-DotNet {
    param([Parameter(Mandatory)][string[]] $Arguments)

    if ($Arguments[0] -eq 'restore') {
        # The evidence source is disposable. Do not require or rewrite its copied
        # lock files, which may have been generated by a different SDK patch.
        $Arguments += @(
            '-p:RestorePackagesWithLockFile=false',
            '-p:RestoreLockedMode=false',
            ("-p:NuGetLockFilePath=$evidenceLockPath")
        )
    }
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
    }
}

function Get-Sha256 {
    param([Parameter(Mandatory)][string] $Path)

    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Get-PeMachine {
    param([Parameter(Mandatory)][string] $Path)

    $bytes = [IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -lt 64 -or $bytes[0] -ne 0x4d -or $bytes[1] -ne 0x5a) {
        throw "Deployment output '$Path' is not an MZ executable."
    }
    $peOffset = [BitConverter]::ToInt32($bytes, 0x3c)
    if ($peOffset -lt 0 -or $peOffset + 6 -gt $bytes.Length -or
        $bytes[$peOffset] -ne 0x50 -or $bytes[$peOffset + 1] -ne 0x45) {
        throw "Deployment output '$Path' has no valid PE signature."
    }
    $machineValue = [BitConverter]::ToUInt16($bytes, $peOffset + 4)
    switch ($machineValue) {
        332 { return 'x86' }
        34404 { return 'x64' }
        43620 { return 'arm64' }
        default { return 'unknown-0x' + $machineValue.ToString('x4') }
    }
}

function Get-VendorAggregate {
    param(
        [Parameter(Mandatory)][string] $ThirdPartyDirectory,
        [Parameter(Mandatory)][string] $ProjectPath
    )

    $root = (Resolve-Path -LiteralPath $ThirdPartyDirectory).Path
    $projectOutput = @(& dotnet msbuild $ProjectPath `
        '-p:Configuration=Release' '-p:Platform=x64' '-getItem:Compile')
    if ($LASTEXITCODE -ne 0) {
        throw 'Could not evaluate the Math project compile allowlist.'
    }
    $evaluatedItems = ($projectOutput -join "`n" | ConvertFrom-Json).Items.Compile
    $paths = [Collections.Generic.List[string]]::new()
    foreach ($item in $evaluatedItems) {
        $fullPath = [string] $item.FullPath
        if ($fullPath.StartsWith($root + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
            $paths.Add($fullPath.Substring($root.Length + 1).Replace('\', '/'))
        }
    }
    @(
        'CSharpMath.Rendering/Reference Fonts/AMS-Capital-Blackboard-Bold.otf',
        'CSharpMath.Rendering/Reference Fonts/cyrillic-modern-nmr10.otf',
        'CSharpMath.Rendering/Reference Fonts/latinmodern-math.otf'
    ) | ForEach-Object { $paths.Add($_) }

    $ordered = [string[]] @($paths.ToArray() | Sort-Object -Unique -CaseSensitive)
    [Array]::Sort($ordered, [StringComparer]::Ordinal)
    $hash = [Security.Cryptography.IncrementalHash]::CreateHash(
        [Security.Cryptography.HashAlgorithmName]::SHA256)
    try {
        foreach ($relative in $ordered) {
            $pathBytes = [Text.Encoding]::UTF8.GetBytes($relative)
            $contentPath = Join-Path $root $relative.Replace('/', '\')
            $contentBytes = [IO.File]::ReadAllBytes($contentPath)
            # Vendor source is text, but the fonts are binary. Normalize only
            # source checkout newlines so Git's CRLF setting cannot alter the
            # audited upstream aggregate.
            if ($relative.EndsWith('.cs', [StringComparison]::OrdinalIgnoreCase)) {
                $content = [Text.Encoding]::UTF8.GetString($contentBytes).Replace("`r`n", "`n", [StringComparison]::Ordinal)
                $contentBytes = [Text.Encoding]::UTF8.GetBytes($content)
            }
            $hash.AppendData([BitConverter]::GetBytes([uint32] $pathBytes.Length))
            $hash.AppendData($pathBytes)
            $hash.AppendData([BitConverter]::GetBytes([uint64] $contentBytes.LongLength))
            $hash.AppendData($contentBytes)
        }
        return [pscustomobject][ordered]@{
            fileCountIncludingFonts = $ordered.Length
            sha256 = [Convert]::ToHexString($hash.GetHashAndReset()).ToLowerInvariant()
            paths = $ordered
        }
    }
    finally {
        $hash.Dispose()
    }
}

function Invoke-CompatibleExecutable {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter(Mandatory)][string] $Rid,
        [Parameter(Mandatory)][string] $HostArchitecture
    )

    $compatible = $Rid -eq ('win-' + $HostArchitecture) -or
        ($HostArchitecture -eq 'x64' -and $Rid -eq 'win-x86')
    if (-not $compatible) {
        return [pscustomobject][ordered]@{
            executed = $false
            exitCode = $null
            output = $null
            reason = "Cross-published $Rid output cannot run on the $HostArchitecture evidence host."
        }
    }

    $output = @(& $Path 2>&1)
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "Deployment smoke '$Path' failed with exit code $exitCode."
    }
    return [pscustomobject][ordered]@{
        executed = $true
        exitCode = $exitCode
        output = ($output -join "`n")
        reason = $null
    }
}

$testsProject = Join-Path $markdownRoot 'MarkdownRenderer.Math.Tests\MarkdownRenderer.Math.Tests.csproj'
$testResultsDirectory = Join-Path $runDirectory 'tests'
$buildArtifactsDirectory = Join-Path $runDirectory 'build'
[IO.Directory]::CreateDirectory($testResultsDirectory) | Out-Null
Push-Location $repositoryRoot
try {
    Invoke-DotNet @(
        'restore', $testsProject,
        '-p:Configuration=Release', '-p:Platform=x64',
        ('-p:ArtifactsPath=' + $buildArtifactsDirectory),
        '--disable-parallel'
    )
    Invoke-DotNet @(
        'test', $testsProject,
        '-c', 'Release', '-p:Platform=x64', '--no-restore',
        ('-p:ArtifactsPath=' + $buildArtifactsDirectory),
        '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
        '--logger', 'trx;LogFileName=math-contracts.trx',
        '--results-directory', $testResultsDirectory
    )

    $packageDirectory = Join-Path $runDirectory 'packages'
    [IO.Directory]::CreateDirectory($packageDirectory) | Out-Null
    Invoke-DotNet @(
        'pack', (Join-Path $markdownRoot 'MarkdownRenderer.Core\MarkdownRenderer.Core.csproj'),
        '-c', 'Release', '-p:Platform=x64', '--no-restore',
        ('-p:ArtifactsPath=' + $buildArtifactsDirectory),
        '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
        '-o', $packageDirectory
    )
    Invoke-DotNet @(
        'pack', (Join-Path $markdownRoot 'MarkdownRenderer.Math\MarkdownRenderer.Math.csproj'),
        '-c', 'Release', '-p:Platform=x64', '--no-restore',
        ('-p:ArtifactsPath=' + $buildArtifactsDirectory),
        '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
        '-o', $packageDirectory
    )
}
finally {
    Pop-Location
}

$trx = [xml] (Get-Content -LiteralPath (Join-Path $testResultsDirectory 'math-contracts.trx') -Raw)
$counters = $trx.TestRun.ResultSummary.Counters
if ([int] $counters.failed -ne 0 -or [int] $counters.executed -ne [int] $counters.passed) {
    throw 'Math contract-test evidence contains a failure or non-passing executed test.'
}

$package = Get-ChildItem -LiteralPath $packageDirectory -Filter 'MarkdownRenderer.Math.*.nupkg' -File |
    Where-Object { $_.Name -notlike '*.symbols.nupkg' } |
    Sort-Object LastWriteTimeUtc -Descending |
    Select-Object -First 1
if ($null -eq $package) { throw 'The Math NuGet package was not produced.' }

$packageCapBytes = [long] (2.3MB)
if ($package.Length -gt $packageCapBytes) {
    throw "MarkdownRenderer.Math is $($package.Length) bytes; the 2.3 MiB gate is $packageCapBytes bytes."
}

$requiredPackageEntries = @(
    'LICENSE',
    'icon-192.png',
    'README.md',
    'THIRD-PARTY-NOTICES.md',
    'UPSTREAM-PATCHES.md',
    'licenses/CSHARPMATH-LICENSE.txt',
    'licenses/TYPOGRAPHY-LICENSE.md',
    'licenses/GUST-FONT-LICENSE.txt',
    'licenses/OFL-1.1.txt',
    'licenses/PROVENANCE.json',
    'lib/net10.0-windows10.0.26100/MarkdownRenderer.Math.dll',
    'lib/net10.0-windows10.0.26100/MarkdownRenderer.Math.xml'
)
$archive = [IO.Compression.ZipFile]::OpenRead($package.FullName)
try {
    $entryNames = @($archive.Entries.FullName)
    foreach ($required in $requiredPackageEntries) {
        if ($required -notin $entryNames) { throw "Math package is missing '$required'." }
    }
    $nativeEntries = @($entryNames | Where-Object { $_ -match '(?i)^runtimes/.+/native/' })
    if ($nativeEntries.Count -ne 0) {
        throw "Math package unexpectedly contains native payload: $($nativeEntries -join ', ')."
    }
    $managedEntry = $archive.GetEntry('lib/net10.0-windows10.0.26100/MarkdownRenderer.Math.dll')
    if ($null -eq $managedEntry) { throw 'Math package has no managed library entry.' }
    $managedBytes = $managedEntry.Length

    $nuspecEntry = $archive.GetEntry('MarkdownRenderer.Math.nuspec')
    if ($null -eq $nuspecEntry) { throw 'Math package has no nuspec.' }
    $reader = [IO.StreamReader]::new($nuspecEntry.Open())
    try { $nuspec = [xml] $reader.ReadToEnd() } finally { $reader.Dispose() }
    $packageVersion = [string] $nuspec.package.metadata.version
    $metadata = $nuspec.package.metadata
    if ([string] $metadata.license.type -ne 'expression' -or [string] $metadata.license.InnerText -ne 'MIT') {
        throw 'Math package must declare the MIT license expression.'
    }
    if ([string] $metadata.icon -ne 'icon-192.png' -or
        [string] $metadata.projectUrl -ne 'https://github.com/JitHubApp/JitHubV2/tree/main/docs/markdown-renderer') {
        throw 'Math package icon/project URL metadata is incomplete.'
    }
    if ([string] $metadata.repository.type -ne 'git' -or
        [string] $metadata.repository.url -ne 'https://github.com/JitHubApp/JitHubV2') {
        throw 'Math package repository/SourceLink metadata is incomplete.'
    }
    $dependencies = @($nuspec.SelectNodes("//*[local-name()='dependency']"))
    if ($dependencies.Count -ne 1 -or $dependencies[0].id -ne 'MarkdownRenderer.Core') {
        throw "Math package must declare exactly one MarkdownRenderer.Core package dependency; found $($dependencies.Count)."
    }
}
finally {
    $archive.Dispose()
}

$thirdPartyDirectory = Join-Path $markdownRoot 'MarkdownRenderer.Math\ThirdParty'
$provenancePath = Join-Path $thirdPartyDirectory 'PROVENANCE.json'
$provenance = Get-Content -LiteralPath $provenancePath -Raw | ConvertFrom-Json
$mathProject = Join-Path $markdownRoot 'MarkdownRenderer.Math\MarkdownRenderer.Math.csproj'
$vendorAggregate = Get-VendorAggregate `
    -ThirdPartyDirectory $thirdPartyDirectory `
    -ProjectPath $mathProject
if ($vendorAggregate.fileCountIncludingFonts -ne [int] $provenance.compiledSnapshot.fileCountIncludingFonts -or
    $vendorAggregate.sha256 -ne [string] $provenance.compiledSnapshot.patchedAggregateSha256) {
    throw 'The compiled Math vendor snapshot no longer matches PROVENANCE.json.'
}
$unsupportedVendorPaths = @($vendorAggregate.paths | Where-Object {
    $_ -match '(?i)(WebFont|BitmapAndSvgFonts|Tables\.Variations|Tables\.TrueType|TrueTypeInterperter|Tables\.Others)'
})
if ($unsupportedVendorPaths.Count -ne 0) {
    throw "The Math compile allowlist contains unsupported general font readers: $($unsupportedVendorPaths -join ', ')."
}
$filesystemWriteSources = @($vendorAggregate.paths | Where-Object { $_ -like '*.cs' } | Where-Object {
    $candidate = Join-Path $thirdPartyDirectory $_.Replace('/', '\')
    Select-String -LiteralPath $candidate -Pattern 'File.WriteAllText' -Quiet
})
if ($filesystemWriteSources.Count -ne 0) {
    throw "The Math compile allowlist contains a filesystem write path: $($filesystemWriteSources -join ', ')."
}
foreach ($font in @($provenance.fonts)) {
    $fontPath = Join-Path $thirdPartyDirectory ('CSharpMath.Rendering\Reference Fonts\' + [string] $font.file)
    if ((Get-Sha256 $fontPath) -ne [string] $font.sha256) {
        throw "Hash mismatch for audited font '$($font.file)'."
    }
}

$complianceDirectory = Join-Path $runDirectory 'package-compliance'
& (Join-Path $PSScriptRoot 'Invoke-PackageCompliance.ps1') `
    -PackageDirectory $packageDirectory `
    -OutputDirectory $complianceDirectory `
    -FailOnUnknownLicense `
    -SkipSizeGates
if ($LASTEXITCODE -ne 0) { throw 'Math package compliance failed.' }

$consumerDirectory = Join-Path $runDirectory 'package-consumer'
[IO.Directory]::CreateDirectory($consumerDirectory) | Out-Null
$consumerProject = @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU' or '$(Platform)' == 'Any CPU'">x64</Platform>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>false</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestoreLockedMode>false</RestoreLockedMode>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <RestorePackagesPath>$(MSBuildProjectDirectory)\packages-cache</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownRenderer.Math" Version="__VERSION__" />
  </ItemGroup>
</Project>
'@.Replace('__VERSION__', $packageVersion)
[IO.File]::WriteAllText(
    (Join-Path $consumerDirectory 'MathPackageConsumer.csproj'),
    $consumerProject,
    [Text.UTF8Encoding]::new($false))
[IO.File]::Copy(
    (Join-Path $markdownRoot 'MarkdownRenderer.Math.AotSmoke\Program.cs'),
    (Join-Path $consumerDirectory 'Program.cs'))

$consumerProjectPath = Join-Path $consumerDirectory 'MathPackageConsumer.csproj'
Push-Location $repositoryRoot
try {
    Invoke-DotNet @(
        'restore', $consumerProjectPath,
        '-p:Configuration=Release', '-p:RestoreLockedMode=false',
        ('-p:RestoreAdditionalProjectSources=' + $packageDirectory),
        '--disable-parallel'
    )
}
finally {
    Pop-Location
}

$hostArchitecture = [Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$matrix = @(
    [pscustomobject]@{ Platform = 'x86'; Rid = 'win-x86'; Machine = 'x86' },
    [pscustomobject]@{ Platform = 'x64'; Rid = 'win-x64'; Machine = 'x64' },
    [pscustomobject]@{ Platform = 'ARM64'; Rid = 'win-arm64'; Machine = 'arm64' }
)
$deployments = [Collections.Generic.List[object]]::new()
foreach ($target in $matrix) {
    foreach ($mode in @('nativeaot', 'trimmed-single-file')) {
        $publishDirectory = Join-Path $runDirectory ($mode + '-' + $target.Rid)
        $arguments = @(
            'publish', $consumerProjectPath,
            '-c', 'Release', '-r', $target.Rid,
            ('-p:Platform=' + $target.Platform),
            '--self-contained', 'true', '--no-restore',
            '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
            '-o', $publishDirectory
        )
        if ($mode -eq 'nativeaot') {
            $arguments += '-p:PublishAot=true'
        }
        else {
            $arguments += @(
                '-p:PublishAot=false', '-p:PublishTrimmed=true', '-p:TrimMode=full',
                '-p:PublishSingleFile=true'
            )
        }

        Push-Location $repositoryRoot
        try { Invoke-DotNet $arguments } finally { Pop-Location }

        $executable = Join-Path $publishDirectory 'MathPackageConsumer.exe'
        if (-not (Test-Path -LiteralPath $executable -PathType Leaf)) {
            throw "$mode $($target.Rid) did not produce a consumer executable."
        }
        $machine = Get-PeMachine $executable
        if ($machine -ne $target.Machine) {
            throw "$mode $($target.Rid) produced a $machine PE instead of $($target.Machine)."
        }
        $execution = Invoke-CompatibleExecutable `
            -Path $executable `
            -Rid $target.Rid `
            -HostArchitecture $hostArchitecture
        $deployments.Add([pscustomobject][ordered]@{
            mode = $mode
            rid = $target.Rid
            peMachine = $machine
            executableBytes = (Get-Item -LiteralPath $executable).Length
            sha256 = Get-Sha256 $executable
            executed = $execution.executed
            exitCode = $execution.exitCode
            output = $execution.output
            skipReason = $execution.reason
        })
    }
}

$report = [pscustomobject][ordered]@{
    schemaVersion = 1
    generatedUtc = [DateTime]::UtcNow.ToString('O', [Globalization.CultureInfo]::InvariantCulture)
    hostArchitecture = $hostArchitecture
    contractTests = [pscustomobject][ordered]@{
        total = [int] $counters.total
        executed = [int] $counters.executed
        passed = [int] $counters.passed
        failed = [int] $counters.failed
        trx = (Join-Path $testResultsDirectory 'math-contracts.trx')
    }
    package = [pscustomobject][ordered]@{
        id = 'MarkdownRenderer.Math'
        version = $packageVersion
        path = $package.FullName
        compressedBytes = $package.Length
        capBytes = $packageCapBytes
        headroomBytes = $packageCapBytes - $package.Length
        managedLibraryBytes = $managedBytes
        nativeAssetCount = $nativeEntries.Count
        packageDependencyCount = $dependencies.Count
        sha256 = Get-Sha256 $package.FullName
    }
    vendorSnapshot = [pscustomobject][ordered]@{
        upstreamCommit = [string] $provenance.upstream.commit
        typographyCommit = [string] $provenance.upstream.typographySubmoduleCommit
        fileCountIncludingFonts = $vendorAggregate.fileCountIncludingFonts
        patchedAggregateSha256 = $vendorAggregate.sha256
        unsupportedGeneralFontReaderCount = $unsupportedVendorPaths.Count
        filesystemWriteSourceCount = $filesystemWriteSources.Count
        provenancePath = $provenancePath
    }
    compliance = [pscustomobject][ordered]@{
        spdx = (Join-Path $complianceDirectory ("MarkdownRenderer.Math.$packageVersion.spdx.json"))
        notices = (Join-Path $complianceDirectory ("MarkdownRenderer.Math.$packageVersion.THIRD-PARTY-NOTICES.md"))
        nativeReport = (Join-Path $complianceDirectory 'native-package-compliance.json')
        reproducibilityManifest = (Join-Path $complianceDirectory 'package-reproducibility.json')
    }
    deployments = @($deployments)
}
$reportPath = Join-Path $runDirectory 'math-release-evidence.json'
[IO.File]::WriteAllText(
    $reportPath,
    ($report | ConvertTo-Json -Depth 20) + "`n",
    [Text.UTF8Encoding]::new($false))

Write-Host "Math release gates passed. Evidence: '$reportPath'."
