[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string] $OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\textmate-release-evidence')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.IO.Compression.FileSystem

$markdownRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $markdownRoot '..')).Path
$runName = 'run-' + [DateTime]::UtcNow.ToString(
    'yyyyMMdd-HHmmssfff',
    [Globalization.CultureInfo]::InvariantCulture)
$runDirectory = [IO.Path]::GetFullPath((Join-Path $OutputDirectory $runName))
[IO.Directory]::CreateDirectory($runDirectory) | Out-Null
$evidenceLockPath = Join-Path $runDirectory 'evidence.packages.lock.json'

function Invoke-DotNet {
    param([Parameter(Mandatory)][string[]] $Arguments)

    if ($Arguments[0] -eq 'restore') {
        # The evidence source is disposable. Do not require or rewrite its copied
        # lock files, which may have been generated by a different SDK patch.
        $Arguments += @(
            '-p:RestorePackagesWithLockFile=false',
            '-p:RestoreLockedMode=false',
            ("-p:NuGetLockFilePath=$evidenceLockPath")
        )
    }
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
    }
}

function Get-Sha256 {
    param([Parameter(Mandatory)][string] $Path)

    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Get-ByteSequenceCount {
    param(
        [Parameter(Mandatory)][string] $HaystackPath,
        [Parameter(Mandatory)][string] $NeedlePath
    )

    # Single-file publishing embeds native libraries in the app bundle rather
    # than leaving them beside the executable. Count the exact payload bytes so
    # the release gate still proves that precisely the selected RID asset was
    # bundled, without depending on runtime extraction implementation details.
    $haystack = [IO.File]::ReadAllBytes($HaystackPath)
    $needle = [IO.File]::ReadAllBytes($NeedlePath)
    if ($needle.Length -eq 0) {
        throw "Cannot search for an empty native payload."
    }

    if (-not ('MarkdownRendererNativeBundleProbe' -as [type])) {
        Add-Type -TypeDefinition @'
using System;
public static class MarkdownRendererNativeBundleProbe
{
    public static int Count(byte[] haystack, byte[] needle)
    {
        var count = 0;
        for (var offset = 0; offset <= haystack.Length - needle.Length; offset++)
        {
            var index = 0;
            for (; index < needle.Length && haystack[offset + index] == needle[index]; index++) { }
            if (index == needle.Length)
            {
                count++;
                offset += needle.Length - 1;
            }
        }
        return count;
    }
}
'@
    }

    return [MarkdownRendererNativeBundleProbe]::Count($haystack, $needle)
}

function Get-PeMachine {
    param([Parameter(Mandatory)][string] $Path)

    $stream = [IO.File]::OpenRead($Path)
    try {
        $reader = [System.Reflection.PortableExecutable.PEReader]::new($stream)
        try { return $reader.PEHeaders.CoffHeader.Machine.ToString() }
        finally { $reader.Dispose() }
    }
    finally {
        $stream.Dispose()
    }
}

function Get-AnyCpuEvidence {
    param([Parameter(Mandatory)][string] $Path)

    $stream = [IO.File]::OpenRead($Path)
    try {
        $reader = [System.Reflection.PortableExecutable.PEReader]::new($stream)
        try {
            $headers = $reader.PEHeaders
            $corHeader = $headers.CorHeader
            if ($null -eq $corHeader) {
                throw "Managed package asset '$Path' has no CLR header."
            }

            $flags = $corHeader.Flags
            $ilOnly = ($flags -band [System.Reflection.PortableExecutable.CorFlags]::ILOnly) -ne 0
            $requires32Bit =
                ($flags -band [System.Reflection.PortableExecutable.CorFlags]::Requires32Bit) -ne 0
            $prefers32Bit =
                ($flags -band [System.Reflection.PortableExecutable.CorFlags]::Prefers32Bit) -ne 0
            $passed = $headers.CoffHeader.Machine.ToString() -eq 'I386' -and
                $headers.PEHeader.Magic.ToString() -eq 'PE32' -and
                $ilOnly -and -not $requires32Bit -and -not $prefers32Bit
            if (-not $passed) {
                throw "Managed package asset '$Path' is not RID-neutral AnyCPU IL."
            }

            return [pscustomobject][ordered]@{
                machine = $headers.CoffHeader.Machine.ToString()
                peMagic = $headers.PEHeader.Magic.ToString()
                corFlags = $flags.ToString()
                ilOnly = $ilOnly
                requires32Bit = $requires32Bit
                prefers32Bit = $prefers32Bit
                bytes = (Get-Item -LiteralPath $Path).Length
                sha256 = Get-Sha256 $Path
                passed = $passed
            }
        }
        finally {
            $reader.Dispose()
        }
    }
    finally {
        $stream.Dispose()
    }
}

function Invoke-CompatibleExecutable {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter(Mandatory)][string] $Rid,
        [Parameter(Mandatory)][string] $HostArchitecture
    )

    $compatible = $Rid -eq ('win-' + $HostArchitecture) -or
        ($HostArchitecture -eq 'x64' -and $Rid -eq 'win-x86')
    if (-not $compatible) {
        return [pscustomobject][ordered]@{
            executed = $false
            exitCode = $null
            output = $null
            reason = "Cross-published $Rid output cannot run on the $HostArchitecture evidence host."
        }
    }

    $output = @(& $Path 2>&1)
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "Deployment smoke '$Path' failed with exit code $exitCode."
    }

    return [pscustomobject][ordered]@{
        executed = $true
        exitCode = $exitCode
        output = ($output -join "`n")
        reason = $null
    }
}

function Get-PackageEvidence {
    param(
        [Parameter(Mandatory)][string] $Directory,
        [Parameter(Mandatory)][string] $Id
    )

    $packageNamePattern = '^{0}\.[0-9]' -f [Regex]::Escape($Id)
    $package = Get-ChildItem -LiteralPath $Directory -Filter '*.nupkg' -File |
        Where-Object {
            $_.Name -notlike '*.symbols.nupkg' -and
            $_.Name -match $packageNamePattern
        } |
        Sort-Object Name |
        Select-Object -First 1
    if ($null -eq $package) {
        throw "NuGet package '$Id' was not produced in '$Directory'."
    }

    $archive = [IO.Compression.ZipFile]::OpenRead($package.FullName)
    try {
        $nuspecEntry = $archive.GetEntry($Id + '.nuspec')
        if ($null -eq $nuspecEntry) { throw "Package '$Id' has no nuspec." }
        $reader = [IO.StreamReader]::new($nuspecEntry.Open())
        try { $nuspec = [xml] $reader.ReadToEnd() }
        finally { $reader.Dispose() }

        return [pscustomobject][ordered]@{
            id = $Id
            version = [string] $nuspec.package.metadata.version
            path = $package.FullName
            compressedBytes = $package.Length
            sha256 = Get-Sha256 $package.FullName
            entries = @($archive.Entries.FullName)
            dependencies = @($nuspec.SelectNodes("//*[local-name()='dependency']") | ForEach-Object {
                [pscustomobject][ordered]@{
                    id = [string] $_.id
                    version = [string] $_.version
                }
            })
        }
    }
    finally {
        $archive.Dispose()
    }
}

function Assert-Dependencies {
    param(
        [Parameter(Mandatory)] $Package,
        [Parameter(Mandatory)][string[]] $Required,
        [string[]] $Forbidden = @()
    )

    $ids = @($Package.dependencies | ForEach-Object { $_.id })
    foreach ($id in $Required) {
        if ($id -notin $ids) {
            throw "Package '$($Package.id)' is missing dependency '$id'."
        }
    }
    foreach ($id in $Forbidden) {
        if ($id -in $ids) {
            throw "Package '$($Package.id)' unexpectedly depends on '$id'."
        }
    }
}

function Assert-PackageEntries {
    param(
        [Parameter(Mandatory)] $Package,
        [Parameter(Mandatory)][string[]] $Required
    )

    foreach ($entry in $Required) {
        if ($entry -notin $Package.entries) {
            throw "Package '$($Package.id)' is missing '$entry'."
        }
    }
    $nativeEntries = @($Package.entries | Where-Object { $_ -match '(?i)^runtimes/.+/native/' })
    if ($nativeEntries.Count -ne 0) {
        throw "Package '$($Package.id)' unexpectedly embeds native assets: $($nativeEntries -join ', ')."
    }
}

function Export-PackageEntry {
    param(
        [Parameter(Mandatory)][string] $PackagePath,
        [Parameter(Mandatory)][string] $EntryPath,
        [Parameter(Mandatory)][string] $DestinationPath
    )

    $archive = [IO.Compression.ZipFile]::OpenRead($PackagePath)
    try {
        $entry = $archive.GetEntry($EntryPath)
        if ($null -eq $entry) {
            throw "Package '$PackagePath' is missing '$EntryPath'."
        }
        [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($DestinationPath)) | Out-Null
        [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $DestinationPath, $true)
    }
    finally {
        $archive.Dispose()
    }
}

$testsProject = Join-Path $markdownRoot `
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Tests\MarkdownRenderer.SyntaxHighlighting.TextMate.Tests.csproj'
$buildArtifactsDirectory = Join-Path $runDirectory 'build'
$restoreProjects = @(
    'MarkdownRenderer.Core\MarkdownRenderer.Core.csproj',
    'MarkdownRenderer\MarkdownRenderer.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate\MarkdownRenderer.SyntaxHighlighting.TextMate.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common\MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All\MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Tests\MarkdownRenderer.SyntaxHighlighting.TextMate.Tests.csproj'
)
$restoreLockDirectory = Join-Path $buildArtifactsDirectory 'locks'
[IO.Directory]::CreateDirectory($restoreLockDirectory) | Out-Null
$testResultsDirectory = Join-Path $runDirectory 'tests'
[IO.Directory]::CreateDirectory($testResultsDirectory) | Out-Null

Push-Location $repositoryRoot
try {
    foreach ($relativeProject in $restoreProjects) {
        $projectName = [IO.Path]::GetFileNameWithoutExtension($relativeProject)
        $restoreLockPath = Join-Path $restoreLockDirectory ($projectName + '.packages.lock.json')
        Invoke-DotNet @(
            'restore', (Join-Path $markdownRoot $relativeProject),
            '-p:Configuration=Release', '-p:Platform=x64', '-p:RestoreRecursive=false',
            ('-p:ArtifactsPath=' + $buildArtifactsDirectory + '\'),
            '-p:RestoreLockedMode=false', '-p:RestorePackagesWithLockFile=true',
            ('-p:NuGetLockFilePath=' + $restoreLockPath),
            '--disable-parallel'
        )
    }
    Invoke-DotNet @(
        'test', $testsProject,
        '-c', 'Release', '-p:Platform=x64', '--no-restore',
        ('-p:ArtifactsPath=' + $buildArtifactsDirectory + '\'),
        '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
        '--logger', 'trx;LogFileName=textmate-contracts.trx',
        '--results-directory', $testResultsDirectory
    )
}
finally {
    Pop-Location
}

$trxPath = Join-Path $testResultsDirectory 'textmate-contracts.trx'
$trx = [xml] (Get-Content -LiteralPath $trxPath -Raw)
$counters = $trx.TestRun.ResultSummary.Counters
if ([int] $counters.failed -ne 0 -or [int] $counters.executed -ne [int] $counters.passed) {
    throw 'TextMate contract-test evidence contains a failure or non-passing executed test.'
}

& (Join-Path $PSScriptRoot 'New-TextMateGrammarProvenance.ps1') -Verify
if ($LASTEXITCODE -ne 0) { throw 'TextMate provenance verification failed.' }

$projects = @(
    'MarkdownRenderer.Core\MarkdownRenderer.Core.csproj',
    'MarkdownRenderer\MarkdownRenderer.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate\MarkdownRenderer.SyntaxHighlighting.TextMate.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common\MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.csproj',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All\MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.csproj'
)
$packageDirectoryA = Join-Path $runDirectory 'packages-a'
$packageDirectoryB = Join-Path $runDirectory 'packages-b'
[IO.Directory]::CreateDirectory($packageDirectoryA) | Out-Null
[IO.Directory]::CreateDirectory($packageDirectoryB) | Out-Null

foreach ($packageDirectory in @($packageDirectoryA, $packageDirectoryB)) {
    foreach ($relativeProject in $projects) {
        Push-Location $repositoryRoot
        try {
            Invoke-DotNet @(
                'pack', (Join-Path $markdownRoot $relativeProject),
                '-c', 'Release', '-p:Platform=x64', '--no-build', '--no-restore',
                ('-p:ArtifactsPath=' + $buildArtifactsDirectory + '\'),
                '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
                '-o', $packageDirectory
            )
        }
        finally {
            Pop-Location
        }
    }

    & (Join-Path $PSScriptRoot 'Normalize-NuGetPackageArchives.ps1') `
        -PackageDirectory $packageDirectory
    if ($LASTEXITCODE -ne 0) { throw 'NuGet timestamp normalization failed.' }
}

$manifestA = Join-Path $runDirectory 'package-reproducibility-a.json'
$manifestB = Join-Path $runDirectory 'package-reproducibility-b.json'
& (Join-Path $PSScriptRoot 'New-PackageReproducibilityManifest.ps1') `
    -PackageDirectory $packageDirectoryA `
    -OutputPath $manifestA
if ($LASTEXITCODE -ne 0) { throw 'Could not create the TextMate package reference manifest.' }
& (Join-Path $PSScriptRoot 'New-PackageReproducibilityManifest.ps1') `
    -PackageDirectory $packageDirectoryB `
    -OutputPath $manifestB `
    -ReferenceManifest $manifestA
if ($LASTEXITCODE -ne 0) { throw 'TextMate package reproducibility failed.' }

$packageIds = @(
    'MarkdownRenderer.Core',
    'MarkdownRenderer.WinUI',
    'MarkdownRenderer.SyntaxHighlighting.TextMate',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common',
    'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All'
)
$packages = [ordered]@{}
foreach ($id in $packageIds) {
    $packages[$id] = Get-PackageEvidence -Directory $packageDirectoryA -Id $id
}

$enginePackage = $packages['MarkdownRenderer.SyntaxHighlighting.TextMate']
$commonPackage = $packages['MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common']
$allPackage = $packages['MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All']
$frameworkPath = 'lib/net10.0-windows10.0.26100/'
$noticeSource = Join-Path $markdownRoot 'eng\textmate\THIRD-PARTY-NOTICES.md'
$provenanceSource = Join-Path $markdownRoot 'eng\textmate\GRAMMAR-PROVENANCE.v2.0.3.json'

Assert-PackageEntries -Package $enginePackage -Required @(
    'README.md',
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.dll'),
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.xml')
)
Assert-PackageEntries -Package $commonPackage -Required @(
    'README.md', 'THIRD-PARTY-NOTICES.md', 'licenses/GRAMMAR-PROVENANCE.json',
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.dll'),
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.xml')
)
Assert-PackageEntries -Package $allPackage -Required @(
    'README.md', 'THIRD-PARTY-NOTICES.md', 'licenses/GRAMMAR-PROVENANCE.json',
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.dll'),
    ($frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.xml')
)
Assert-Dependencies -Package $enginePackage `
    -Required @('MarkdownRenderer.WinUI') `
    -Forbidden @('TextMateSharp', 'TextMateSharp.Grammars', 'Onigwrap')
Assert-Dependencies -Package $commonPackage `
    -Required @('MarkdownRenderer.SyntaxHighlighting.TextMate', 'TextMateSharp') `
    -Forbidden @('TextMateSharp.Grammars')
Assert-Dependencies -Package $allPackage `
    -Required @('MarkdownRenderer.SyntaxHighlighting.TextMate', 'TextMateSharp.Grammars')

$commonCapBytes = [long] (6MB)
if ($commonPackage.compressedBytes -gt $commonCapBytes) {
    throw "Common grammar pack is $($commonPackage.compressedBytes) bytes; its 6 MiB cap is $commonCapBytes."
}

$extractedDirectory = Join-Path $runDirectory 'package-assets'
$managedPackageAssets = @(
    [pscustomobject]@{
        Package = $enginePackage
        Entry = $frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.dll'
        File = 'MarkdownRenderer.SyntaxHighlighting.TextMate.dll'
    },
    [pscustomobject]@{
        Package = $commonPackage
        Entry = $frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.dll'
        File = 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.dll'
    },
    [pscustomobject]@{
        Package = $allPackage
        Entry = $frameworkPath + 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.dll'
        File = 'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All.dll'
    }
)
$managedArchitecture = [Collections.Generic.List[object]]::new()
foreach ($asset in $managedPackageAssets) {
    $path = Join-Path $extractedDirectory $asset.File
    Export-PackageEntry -PackagePath $asset.Package.path -EntryPath $asset.Entry -DestinationPath $path
    $managedArchitecture.Add([pscustomobject][ordered]@{
        package = $asset.Package.id
        asset = $asset.Entry
        evidence = Get-AnyCpuEvidence $path
    })
}

foreach ($pack in @($commonPackage, $allPackage)) {
    $packNotice = Join-Path $extractedDirectory ($pack.id + '.THIRD-PARTY-NOTICES.md')
    $packProvenance = Join-Path $extractedDirectory ($pack.id + '.GRAMMAR-PROVENANCE.json')
    Export-PackageEntry -PackagePath $pack.path `
        -EntryPath 'THIRD-PARTY-NOTICES.md' -DestinationPath $packNotice
    Export-PackageEntry -PackagePath $pack.path `
        -EntryPath 'licenses/GRAMMAR-PROVENANCE.json' -DestinationPath $packProvenance
    if ((Get-Sha256 $packNotice) -ne (Get-Sha256 $noticeSource)) {
        throw "Package '$($pack.id)' notice payload differs from the reviewed source."
    }
    if ((Get-Sha256 $packProvenance) -ne (Get-Sha256 $provenanceSource)) {
        throw "Package '$($pack.id)' provenance payload differs from the reviewed source."
    }
}

$complianceDirectory = Join-Path $runDirectory 'package-compliance'
& (Join-Path $PSScriptRoot 'Invoke-PackageCompliance.ps1') `
    -PackageDirectory $packageDirectoryA `
    -OutputDirectory $complianceDirectory `
    -FailOnUnknownLicense `
    -SkipSizeGates
if ($LASTEXITCODE -ne 0) { throw 'TextMate package compliance failed.' }

# Keep the compiler/tool path below legacy MAX_PATH-sensitive WinUI tooling.
$consumerDirectory = Join-Path $markdownRoot ('artifacts\tm\' + $runName)
$consumerPackagesDirectory = Join-Path $markdownRoot ('artifacts\tm\p-' + $runName)
[IO.Directory]::CreateDirectory($consumerDirectory) | Out-Null
[IO.Directory]::CreateDirectory($consumerPackagesDirectory) | Out-Null
$consumerProject = (@'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platform Condition="'$(Platform)' == '' or '$(Platform)' == 'AnyCPU' or '$(Platform)' == 'Any CPU'">x64</Platform>
    <InvariantGlobalization>false</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
    <!-- Windows SDK 10.0.26100.57 / CsWinRT 2.3.1 issue IL2081 for generated
         WinRT ABI fallbacks. Keep the exception scoped to single-file
         packaging; NativeAOT and every other linker diagnostic remain fatal. -->
    <NoWarn Condition="'$(PublishSingleFile)' == 'true'">$(NoWarn);IL2081</NoWarn>
    <WindowsAppSDKSelfContained Condition="'$(PublishSingleFile)' == 'true'">true</WindowsAppSDKSelfContained>
    <RestoreLockedMode>false</RestoreLockedMode>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <RestorePackagesPath>__CONSUMER_PACKAGES__</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common" Version="__COMMON_VERSION__" />
    <PackageReference Include="MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.All" Version="__ALL_VERSION__" />
  </ItemGroup>
</Project>
'@).Replace('__CONSUMER_PACKAGES__', [Security.SecurityElement]::Escape($consumerPackagesDirectory)).Replace(
    '__COMMON_VERSION__',
    $commonPackage.version).Replace(
    '__ALL_VERSION__',
    $allPackage.version)
[IO.File]::WriteAllText(
    (Join-Path $consumerDirectory 'TextMatePackageConsumer.csproj'),
    $consumerProject,
    [Text.UTF8Encoding]::new($false))
[IO.File]::Copy(
    (Join-Path $markdownRoot 'MarkdownRenderer.SyntaxHighlighting.TextMate.AotSmoke\Program.cs'),
    (Join-Path $consumerDirectory 'Program.cs'))

$consumerProjectPath = Join-Path $consumerDirectory 'TextMatePackageConsumer.csproj'
Push-Location $repositoryRoot
try {
    Invoke-DotNet @(
        'restore', $consumerProjectPath,
        '-p:Configuration=Release', '-p:RestoreLockedMode=false',
        ('-p:RestoreAdditionalProjectSources=' + $packageDirectoryA),
        '--disable-parallel'
    )
}
finally {
    Pop-Location
}

$hostArchitecture = [Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$matrix = @(
    [pscustomobject]@{ Platform = 'x86'; Rid = 'win-x86'; Machine = 'I386' },
    [pscustomobject]@{ Platform = 'x64'; Rid = 'win-x64'; Machine = 'Amd64' },
    [pscustomobject]@{ Platform = 'ARM64'; Rid = 'win-arm64'; Machine = 'Arm64' }
)
$deployments = [Collections.Generic.List[object]]::new()
$selectedPayloads = [Collections.Generic.List[object]]::new()

foreach ($target in $matrix) {
    $portableDirectory = Join-Path $runDirectory ('selected-rid-' + $target.Rid)
    Push-Location $repositoryRoot
    try {
        Invoke-DotNet @(
            'publish', $consumerProjectPath,
            '-c', 'Release', '-r', $target.Rid,
            ('-p:Platform=' + $target.Platform),
            '--self-contained', 'false', '--no-restore',
            '-p:PublishAot=false', '-p:PublishTrimmed=false', '-p:PublishSingleFile=false',
            '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
            '-o', $portableDirectory
        )
    }
    finally {
        Pop-Location
    }

    $payloadNames = @(
        'MarkdownRenderer.SyntaxHighlighting.TextMate.dll',
        'MarkdownRenderer.SyntaxHighlighting.TextMate.Grammars.Common.dll',
        'TextMateSharp.dll',
        'Onigwrap.dll',
        'libonigwrap.dll'
    )
    $payloadFiles = [Collections.Generic.List[IO.FileInfo]]::new()
    foreach ($name in $payloadNames) {
        $matches = @(Get-ChildItem -LiteralPath $portableDirectory -Recurse -File -Filter $name)
        if ($matches.Count -ne 1) {
            throw "Selected-RID output '$($target.Rid)' contains $($matches.Count) copies of '$name'; expected one."
        }
        $payloadFiles.Add($matches[0])
    }
    $selectedBytes = [long] (($payloadFiles | Measure-Object Length -Sum).Sum)
    if ($selectedBytes -gt $commonCapBytes) {
        throw "Selected-RID Common payload for '$($target.Rid)' is $selectedBytes bytes; cap is $commonCapBytes."
    }
    $selectedNative = $payloadFiles | Where-Object { $_.Name -eq 'libonigwrap.dll' } | Select-Object -First 1
    $selectedMachine = Get-PeMachine $selectedNative.FullName
    if ($selectedMachine -ne $target.Machine) {
        throw "Selected-RID Onigwrap for '$($target.Rid)' is $selectedMachine, expected $($target.Machine)."
    }
    $selectedPayloads.Add([pscustomobject][ordered]@{
        rid = $target.Rid
        bytes = $selectedBytes
        capBytes = $commonCapBytes
        headroomBytes = $commonCapBytes - $selectedBytes
        nativeMachine = $selectedMachine
        files = @($payloadFiles | ForEach-Object {
            [pscustomobject][ordered]@{
                name = $_.Name
                bytes = $_.Length
                sha256 = Get-Sha256 $_.FullName
                managedArchitecture = if ($_.Name -eq 'libonigwrap.dll') {
                    $null
                }
                else {
                    Get-AnyCpuEvidence $_.FullName
                }
            }
        })
    })

    foreach ($mode in @('nativeaot', 'trimmed-single-file')) {
        $publishDirectory = Join-Path $runDirectory ($mode + '-' + $target.Rid)
        $arguments = @(
            'publish', $consumerProjectPath,
            '-c', 'Release', '-r', $target.Rid,
            ('-p:Platform=' + $target.Platform),
            '--self-contained', 'true',
            ('-p:RestoreAdditionalProjectSources=' + $packageDirectoryA),
            '--disable-build-servers', '-p:UseSharedCompilation=false', '-nr:false',
            '-o', $publishDirectory
        )
        if ($mode -eq 'nativeaot') {
            $arguments += @(
                '-p:PublishAot=true', '-p:PublishSingleFile=false',
                '-p:UseAppHost=true'
            )
        }
        else {
            $arguments += @(
                '-p:PublishAot=false', '-p:PublishTrimmed=true', '-p:TrimMode=full',
                '-p:PublishSingleFile=true', '-p:EnableMsixTooling=true'
            )
        }

        Push-Location $repositoryRoot
        try { Invoke-DotNet $arguments }
        finally { Pop-Location }

        $executable = Join-Path $publishDirectory 'TextMatePackageConsumer.exe'
        if (-not (Test-Path -LiteralPath $executable -PathType Leaf)) {
            throw "$mode $($target.Rid) did not produce a consumer executable."
        }
        if ($mode -eq 'nativeaot' -and (Test-Path -LiteralPath (Join-Path $publishDirectory 'TextMatePackageConsumer.dll') -PathType Leaf)) {
            throw "nativeaot $($target.Rid) published a managed consumer DLL instead of a NativeAOT executable."
        }
        $machine = Get-PeMachine $executable
        if ($machine -ne $target.Machine) {
            throw "$mode $($target.Rid) produced a $machine PE instead of $($target.Machine)."
        }
        $nativeAssets = @(Get-ChildItem -LiteralPath $publishDirectory -Recurse -File -Filter 'libonigwrap.dll')
        $nativeMachine = Get-PeMachine $selectedNative.FullName
        $nativeBytes = $selectedNative.Length
        $nativeSha256 = Get-Sha256 $selectedNative.FullName
        $nativeBundleOccurrences = $null
        if ($mode -eq 'nativeaot') {
            if ($nativeAssets.Count -ne 1) {
                throw "$mode $($target.Rid) contains $($nativeAssets.Count) selected Onigwrap native assets; expected one."
            }
            $nativeMachine = Get-PeMachine $nativeAssets[0].FullName
            if ($nativeMachine -ne $target.Machine) {
                throw "$mode $($target.Rid) selected $nativeMachine Onigwrap instead of $($target.Machine)."
            }
            $nativeBytes = $nativeAssets[0].Length
            $nativeSha256 = Get-Sha256 $nativeAssets[0].FullName
        }
        else {
            if ($nativeAssets.Count -ne 0) {
                throw "$mode $($target.Rid) left $($nativeAssets.Count) loose Onigwrap native assets; expected the payload to be bundled."
            }
            $nativeBundleOccurrences = Get-ByteSequenceCount -HaystackPath $executable -NeedlePath $selectedNative.FullName
            if ($nativeBundleOccurrences -ne 1) {
                throw "$mode $($target.Rid) bundles $nativeBundleOccurrences copies of the selected Onigwrap native payload; expected one."
            }
        }

        $execution = Invoke-CompatibleExecutable `
            -Path $executable `
            -Rid $target.Rid `
            -HostArchitecture $hostArchitecture
        $deployments.Add([pscustomobject][ordered]@{
            mode = $mode
            rid = $target.Rid
            peMachine = $machine
            executableBytes = (Get-Item -LiteralPath $executable).Length
            sha256 = Get-Sha256 $executable
            selectedNativeMachine = $nativeMachine
            selectedNativeBytes = $nativeBytes
            selectedNativeSha256 = $nativeSha256
            selectedNativeBundleOccurrences = $nativeBundleOccurrences
            executed = $execution.executed
            exitCode = $execution.exitCode
            output = $execution.output
            skipReason = $execution.reason
        })
    }
}

$provenance = Get-Content -LiteralPath $provenanceSource -Raw | ConvertFrom-Json -Depth 100
$textMateSharpProvenance = @($provenance.upstreamPackages | Where-Object {
    $_.id -eq 'TextMateSharp'
})
if ($textMateSharpProvenance.Count -ne 1) {
    throw "Expected exactly one TextMateSharp provenance record; found $($textMateSharpProvenance.Count)."
}
$textMateSharpProvenance = $textMateSharpProvenance[0]
$report = [pscustomobject][ordered]@{
    schemaVersion = 1
    generatedUtc = [DateTime]::UtcNow.ToString('O', [Globalization.CultureInfo]::InvariantCulture)
    hostArchitecture = $hostArchitecture
    scope = 'TextMate engine, Common grammar pack, All grammar pack, packaging, and deployment consumers'
    contractTests = [pscustomobject][ordered]@{
        total = [int] $counters.total
        executed = [int] $counters.executed
        passed = [int] $counters.passed
        failed = [int] $counters.failed
        trx = $trxPath
    }
    provenance = [pscustomobject][ordered]@{
        textMateSharpVersion = [string] $textMateSharpProvenance.version
        textMateSharpCommit = [string] $textMateSharpProvenance.commit
        grammarResourceCount = [int] $provenance.allPack.resourceCount
        registrationCount = [int] $provenance.registrations.Count
        detailedLicenseRegistrationCount = [int] $provenance.licenseDetailRegistrationCount
        commonResourceCount = [int] $provenance.commonPack.resourceCount
        aggregateSha256 = [string] $provenance.allPack.aggregateSha256
        source = $provenanceSource
        verified = $true
    }
    packages = @($packages.Values | ForEach-Object {
        [pscustomobject][ordered]@{
            id = $_.id
            version = $_.version
            path = $_.path
            compressedBytes = $_.compressedBytes
            sha256 = $_.sha256
            dependencies = $_.dependencies
        }
    })
    commonPackageGate = [pscustomobject][ordered]@{
        compressedBytes = $commonPackage.compressedBytes
        capBytes = $commonCapBytes
        headroomBytes = $commonCapBytes - $commonPackage.compressedBytes
        passed = $commonPackage.compressedBytes -le $commonCapBytes
    }
    selectedRidCommonPayloads = @($selectedPayloads)
    managedPackageArchitecture = @($managedArchitecture)
    packageReproducibility = [pscustomobject][ordered]@{
        referenceManifest = $manifestA
        candidateManifest = $manifestB
        passed = $true
    }
    compliance = [pscustomobject][ordered]@{
        directory = $complianceDirectory
        summary = (Join-Path $complianceDirectory 'compliance-summary.json')
        nativeReport = (Join-Path $complianceDirectory 'native-package-compliance.json')
        reproducibilityManifest = (Join-Path $complianceDirectory 'package-reproducibility.json')
        failOnUnknownLicense = $true
        passed = $true
    }
    deployments = @($deployments)
    physicalRuntimeGaps = @(
        'ARM64 binaries were cross-published and statically validated but cannot execute on this x64 host.',
        'This gate does not replace physical x64/ARM64 ETW performance runs or UI-thread/frame-time gates.',
        'NativeAOT and trimmed single-file checks are unpackaged console consumers; packaged MSIX consumption remains a separate release-matrix gate.'
    )
}
$reportPath = Join-Path $runDirectory 'textmate-release-evidence.json'
[IO.File]::WriteAllText(
    $reportPath,
    ($report | ConvertTo-Json -Depth 30) + "`n",
    [Text.UTF8Encoding]::new($false))

Write-Host "TextMate release gates passed. Evidence: '$reportPath'."
