using System.Text.Json.Serialization;
using JitHub.Models.GitHub;

namespace JitHub.Services;

[JsonSerializable(typeof(GitHubRepository))]
[JsonSerializable(typeof(GitHubRepository[]))]
[JsonSerializable(typeof(GitHubResourceState))]
[JsonSerializable(typeof(GitHubRepositorySubscription))]
[JsonSerializable(typeof(GitHubStarredRepository))]
[JsonSerializable(typeof(GitHubStarredRepository[]))]
[JsonSerializable(typeof(GitHubRepositorySearchResponse))]
[JsonSerializable(typeof(GitHubUser))]
[JsonSerializable(typeof(GitHubProfileGraphQlData))]
[JsonSerializable(typeof(GitHubProfileGraphQlUser))]
[JsonSerializable(typeof(GitHubProfileStatus))]
[JsonSerializable(typeof(GitHubProfileContributionsCollection))]
[JsonSerializable(typeof(GitHubProfileContributionCalendarPayload))]
[JsonSerializable(typeof(GitHubProfileContributionWeekPayload[]))]
[JsonSerializable(typeof(GitHubProfileContributionDayPayload[]))]
[JsonSerializable(typeof(GitHubProfilePinnedItemsConnection))]
[JsonSerializable(typeof(GitHubProfilePinnedItemNode[]))]
[JsonSerializable(typeof(GitHubProfileLanguage))]
[JsonSerializable(typeof(GitHubOrganization))]
[JsonSerializable(typeof(GitHubOrganization[]))]
[JsonSerializable(typeof(GitHubActivityEvent[]))]
[JsonSerializable(typeof(GitHubNotificationThread[]))]
[JsonSerializable(typeof(GitHubNotificationSubscription))]
[JsonSerializable(typeof(GitHubSearchCountResponse))]
[JsonSerializable(typeof(GitHubSearchIssuesResponse))]
[JsonSerializable(typeof(GitHubIssue))]
[JsonSerializable(typeof(GitHubIssue[]))]
[JsonSerializable(typeof(GitHubIssueComment[]))]
[JsonSerializable(typeof(GitHubIssueEvent[]))]
[JsonSerializable(typeof(GitHubReaction[]))]
[JsonSerializable(typeof(GitHubActor[]))]
[JsonSerializable(typeof(GitHubLabel[]))]
[JsonSerializable(typeof(GitHubMilestone[]))]
[JsonSerializable(typeof(GitHubPullRequest))]
[JsonSerializable(typeof(GitHubPullRequest[]))]
[JsonSerializable(typeof(GitHubCommit[]))]
[JsonSerializable(typeof(GitHubCommit))]
[JsonSerializable(typeof(GitHubCommitFile[]))]
[JsonSerializable(typeof(GitHubBranch[]))]
[JsonSerializable(typeof(GitHubCommitComment[]))]
[JsonSerializable(typeof(GitHubCombinedStatus))]
[JsonSerializable(typeof(GitHubCheckRunResponse))]
[JsonSerializable(typeof(GitHubCompareResult))]
[JsonSerializable(typeof(GitHubPullRequestReview[]))]
[JsonSerializable(typeof(GitHubPullRequestReviewComment[]))]
[JsonSerializable(typeof(GitHubGist[]))]
[JsonSerializable(typeof(GitHubGist))]
[JsonSerializable(typeof(GitHubTree))]
[JsonSerializable(typeof(GitHubRepositoryContent[]))]
[JsonSerializable(typeof(GitHubBlob))]
internal sealed partial class Phase0GitHubJsonSerializerContext : JsonSerializerContext
{
}
