# Copyright (c) Riverside Valley Corporation
name: ✨ Feature Request
description: Request a new feature to make things better!
labels: [feature request]
title: "✨ "
body:
  - type: markdown
    attributes:
      value: |
        ##### ⏱️ Before you start...
        - Have you checked whether or not a similar feature request has already been reported?
  - type: textarea
    attributes:
      label: 📄 Description
      description: A clear and concise description of what your idea is. Include things like possible use cases, drawbacks, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🗃️ Alternative solutions
      description: Describe more ways this idea could be implemented.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: Give an overview of all the specific things you would like to be changed or implemented.
      value: |
        ```[tasklist]
        ### High Priority
        - [ ] Something
        - [ ] Another thing
        - [ ] https://github.com/link/to/an/issue
        ```
        ```[tasklist]
        ### Nice to have
        - [ ] Something
        - [ ] Another thing
        - [ ] https://github.com/link/to/an/issue
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📸 Assets
      description: A list of assets (screenshots, mockups) relevant to this feature request.
    validations:
      required: false
