// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    namespace System.SystemServices
    {
        [Flags]
        [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
        internal enum MODIFIERKEYS_FLAGS : uint
        {
            MK_LBUTTON = 0x00000001,
            MK_RBUTTON = 0x00000002,
            MK_SHIFT = 0x00000004,
            MK_CONTROL = 0x00000008,
            MK_MBUTTON = 0x00000010,
            MK_XBUTTON1 = 0x00000020,
            MK_XBUTTON2 = 0x00000040,
        }
    }
}
