using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("MarkdownRenderer.Gfm")]
[assembly: InternalsVisibleTo("MarkdownRenderer.GitHub")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Html")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Html.Tests")]
[assembly: InternalsVisibleTo("MarkdownRenderer.GitHub.Tests")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Tests")]
[assembly: InternalsVisibleTo("MarkdownRenderer.PixelTests")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Sample")]
[assembly: InternalsVisibleTo("MarkdownRenderer.PerformanceHarness")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Performance")]
[assembly: InternalsVisibleTo("MarkdownRenderer.Svg.Resvg")]
[assembly: InternalsVisibleTo("MarkdownRenderer.SyntaxHighlighting.TextMate")]
[assembly: InternalsVisibleTo("JitHub.WinUI")]
