using System.Collections.Generic;
using System.Text.Json.Serialization;
using JitHub.Services;

namespace JitHub.Models.GitHub;

[JsonSerializable(typeof(GitHubUser))]
[JsonSerializable(typeof(GitHubUser[]))]
[JsonSerializable(typeof(GitHubUserProfileUpdateRequest))]
[JsonSerializable(typeof(GitHubGraphQlRequest))]
[JsonSerializable(typeof(GitHubGraphQlResponse<GitHubProfileGraphQlData>))]
[JsonSerializable(typeof(GitHubProfileGraphQlData))]
[JsonSerializable(typeof(GitHubProfileGraphQlUser))]
[JsonSerializable(typeof(GitHubProfileStatus))]
[JsonSerializable(typeof(GitHubProfileContributionsCollection))]
[JsonSerializable(typeof(GitHubProfileContributionCalendarPayload))]
[JsonSerializable(typeof(GitHubProfileContributionWeekPayload[]))]
[JsonSerializable(typeof(GitHubProfileContributionDayPayload[]))]
[JsonSerializable(typeof(GitHubProfilePinnedItemsConnection))]
[JsonSerializable(typeof(GitHubProfilePinnedItemNode[]))]
[JsonSerializable(typeof(GitHubProfileLanguage))]
[JsonSerializable(typeof(GitHubOrganization))]
[JsonSerializable(typeof(GitHubOrganization[]))]
[JsonSerializable(typeof(GitHubRepository))]
[JsonSerializable(typeof(GitHubStarredRepository))]
[JsonSerializable(typeof(GitHubStarredRepository[]))]
[JsonSerializable(typeof(GitHubRepositoryContent))]
[JsonSerializable(typeof(GitHubBlob))]
[JsonSerializable(typeof(GitHubIssue))]
[JsonSerializable(typeof(GitHubIssueComment))]
[JsonSerializable(typeof(GitHubCommitComment))]
[JsonSerializable(typeof(GitHubCommitCommentCreateRequest))]
[JsonSerializable(typeof(GitHubCompareResult))]
[JsonSerializable(typeof(GitHubCombinedStatus))]
[JsonSerializable(typeof(GitHubCommitStatus))]
[JsonSerializable(typeof(GitHubPullRequest))]
[JsonSerializable(typeof(GitHubCheckRun))]
[JsonSerializable(typeof(GitHubCheckRunResponse))]
[JsonSerializable(typeof(GitHubPullRequestReview))]
[JsonSerializable(typeof(GitHubPullRequestReviewComment))]
[JsonSerializable(typeof(GitHubReaction))]
[JsonSerializable(typeof(GitHubReactionSummary))]
[JsonSerializable(typeof(GitHubIssueEvent))]
[JsonSerializable(typeof(GitHubPullRequestMergeResult))]
[JsonSerializable(typeof(GitHubRepositorySubscription))]
[JsonSerializable(typeof(GitHubCommit))]
[JsonSerializable(typeof(GitHubActivityEvent))]
[JsonSerializable(typeof(CommitCommentEventPayload))]
[JsonSerializable(typeof(CreateEventPayload))]
[JsonSerializable(typeof(DeleteEventPayload))]
[JsonSerializable(typeof(DiscussionEventPayload))]
[JsonSerializable(typeof(ForkEventPayload))]
[JsonSerializable(typeof(GollumEventPayload))]
[JsonSerializable(typeof(IssueCommentEventPayload))]
[JsonSerializable(typeof(IssuesEventPayload))]
[JsonSerializable(typeof(MemberEventPayload))]
[JsonSerializable(typeof(PublicEventPayload))]
[JsonSerializable(typeof(PullRequestEventPayload))]
[JsonSerializable(typeof(PullRequestReviewEventPayload))]
[JsonSerializable(typeof(PullRequestReviewCommentEventPayload))]
[JsonSerializable(typeof(PushEventPayload))]
[JsonSerializable(typeof(ReleaseEventPayload))]
[JsonSerializable(typeof(WatchEventPayload))]
[JsonSerializable(typeof(GitHubActivityDiscussion))]
[JsonSerializable(typeof(GitHubActivityWikiPage))]
[JsonSerializable(typeof(GitHubActivityWikiPage[]))]
[JsonSerializable(typeof(GitHubActivityPushCommit))]
[JsonSerializable(typeof(GitHubActivityPushCommit[]))]
[JsonSerializable(typeof(GitHubActivityCommitAuthor))]
[JsonSerializable(typeof(GitHubActivityRelease))]
[JsonSerializable(typeof(GitHubLabel))]
[JsonSerializable(typeof(GitHubMilestone))]
[JsonSerializable(typeof(GitHubRepository[]))]
[JsonSerializable(typeof(GitHubBranch[]))]
[JsonSerializable(typeof(GitHubIssue[]))]
[JsonSerializable(typeof(GitHubIssueComment[]))]
[JsonSerializable(typeof(GitHubPullRequest[]))]
[JsonSerializable(typeof(GitHubPullRequestReview[]))]
[JsonSerializable(typeof(GitHubPullRequestReviewComment[]))]
[JsonSerializable(typeof(GitHubReaction[]))]
[JsonSerializable(typeof(GitHubIssueEvent[]))]
[JsonSerializable(typeof(GitHubCommit[]))]
[JsonSerializable(typeof(GitHubActivityEvent[]))]
[JsonSerializable(typeof(GitHubActor[]))]
[JsonSerializable(typeof(GitHubLabel[]))]
[JsonSerializable(typeof(GitHubMilestone[]))]
[JsonSerializable(typeof(GitHubRepositoryContent[]))]
[JsonSerializable(typeof(GitHubCommitComment[]))]
[JsonSerializable(typeof(GitHubCommitStatus[]))]
[JsonSerializable(typeof(GitHubCheckRun[]))]
[JsonSerializable(typeof(GitHubRepositoryCreateRequest))]
[JsonSerializable(typeof(GitHubIssueCreateRequest))]
[JsonSerializable(typeof(GitHubIssueUpdateRequest))]
[JsonSerializable(typeof(GitHubIssueMetadataUpdateRequest))]
[JsonSerializable(typeof(GitHubIssueCommentCreateRequest))]
[JsonSerializable(typeof(GitHubPullRequestCreateRequest))]
[JsonSerializable(typeof(GitHubPullRequestUpdateRequest))]
[JsonSerializable(typeof(GitHubPullRequestMergeRequest))]
[JsonSerializable(typeof(GitHubPullRequestReviewersUpdateRequest))]
[JsonSerializable(typeof(GitHubPullRequestReviewCreateRequest))]
[JsonSerializable(typeof(GitHubReactionCreateRequest))]
[JsonSerializable(typeof(GitHubRepositorySubscriptionRequest))]
[JsonSerializable(typeof(GitHubRepositorySearchResponse))]
[JsonSerializable(typeof(GitHubNotificationThread))]
[JsonSerializable(typeof(GitHubNotificationThread[]))]
[JsonSerializable(typeof(GitHubNotificationSubject))]
[JsonSerializable(typeof(GitHubNotificationSubscription))]
[JsonSerializable(typeof(GitHubNotificationMarkReadRequest))]
[JsonSerializable(typeof(GitHubNotificationSubscriptionUpdateRequest))]
[JsonSerializable(typeof(GitHubSearchCountResponse))]
[JsonSerializable(typeof(GitHubSearchIssuesResponse))]
[JsonSerializable(typeof(GitHubGist))]
[JsonSerializable(typeof(GitHubGist[]))]
[JsonSerializable(typeof(GitHubGistFile))]
[JsonSerializable(typeof(Dictionary<string, GitHubGistFile>))]
[JsonSerializable(typeof(GitHubGistCreateRequest))]
[JsonSerializable(typeof(GitHubGistUpdateRequest))]
[JsonSerializable(typeof(GitHubGistFileWriteRequest))]
[JsonSerializable(typeof(GitHubGistFileUpdateRequest))]
[JsonSerializable(typeof(Dictionary<string, GitHubGistFileWriteRequest>))]
[JsonSerializable(typeof(Dictionary<string, GitHubGistFileUpdateRequest?>))]
[JsonSerializable(typeof(GitHubApiError))]
[JsonSerializable(typeof(GitHubTree))]
[JsonSerializable(typeof(GitHubTreeEntry))]
[JsonSerializable(typeof(GitHubTreeEntry[]))]
internal partial class GitHubJsonSerializerContext : JsonSerializerContext
{
}

internal sealed class GitHubApiError
{
    [JsonPropertyName("message")]
    public string? Message { get; init; }
}
