using System.Text.Json.Serialization;

namespace JitHub.Models.GitHub;

[JsonSerializable(typeof(GitHubUser))]
[JsonSerializable(typeof(GitHubRepository))]
[JsonSerializable(typeof(GitHubRepositoryContent))]
[JsonSerializable(typeof(GitHubBlob))]
[JsonSerializable(typeof(GitHubIssue))]
[JsonSerializable(typeof(GitHubIssueComment))]
[JsonSerializable(typeof(GitHubCommitComment))]
[JsonSerializable(typeof(GitHubCompareResult))]
[JsonSerializable(typeof(GitHubPullRequest))]
[JsonSerializable(typeof(GitHubCheckRun))]
[JsonSerializable(typeof(GitHubCheckRunResponse))]
[JsonSerializable(typeof(GitHubPullRequestReview))]
[JsonSerializable(typeof(GitHubPullRequestReviewComment))]
[JsonSerializable(typeof(GitHubReaction))]
[JsonSerializable(typeof(GitHubReactionSummary))]
[JsonSerializable(typeof(GitHubIssueEvent))]
[JsonSerializable(typeof(GitHubPullRequestMergeResult))]
[JsonSerializable(typeof(GitHubRepositorySubscription))]
[JsonSerializable(typeof(GitHubCommit))]
[JsonSerializable(typeof(GitHubActivityEvent))]
[JsonSerializable(typeof(GitHubLabel))]
[JsonSerializable(typeof(GitHubMilestone))]
[JsonSerializable(typeof(GitHubRepository[]))]
[JsonSerializable(typeof(GitHubBranch[]))]
[JsonSerializable(typeof(GitHubIssue[]))]
[JsonSerializable(typeof(GitHubIssueComment[]))]
[JsonSerializable(typeof(GitHubPullRequest[]))]
[JsonSerializable(typeof(GitHubPullRequestReview[]))]
[JsonSerializable(typeof(GitHubPullRequestReviewComment[]))]
[JsonSerializable(typeof(GitHubReaction[]))]
[JsonSerializable(typeof(GitHubIssueEvent[]))]
[JsonSerializable(typeof(GitHubCommit[]))]
[JsonSerializable(typeof(GitHubActivityEvent[]))]
[JsonSerializable(typeof(GitHubActor[]))]
[JsonSerializable(typeof(GitHubLabel[]))]
[JsonSerializable(typeof(GitHubMilestone[]))]
[JsonSerializable(typeof(GitHubRepositoryContent[]))]
[JsonSerializable(typeof(GitHubCommitComment[]))]
[JsonSerializable(typeof(GitHubCheckRun[]))]
[JsonSerializable(typeof(GitHubRepositoryCreateRequest))]
[JsonSerializable(typeof(GitHubIssueCreateRequest))]
[JsonSerializable(typeof(GitHubIssueUpdateRequest))]
[JsonSerializable(typeof(GitHubIssueMetadataUpdateRequest))]
[JsonSerializable(typeof(GitHubIssueCommentCreateRequest))]
[JsonSerializable(typeof(GitHubPullRequestCreateRequest))]
[JsonSerializable(typeof(GitHubPullRequestUpdateRequest))]
[JsonSerializable(typeof(GitHubPullRequestMergeRequest))]
[JsonSerializable(typeof(GitHubPullRequestReviewersUpdateRequest))]
[JsonSerializable(typeof(GitHubReactionCreateRequest))]
[JsonSerializable(typeof(GitHubRepositorySubscriptionRequest))]
[JsonSerializable(typeof(GitHubRepositorySearchResponse))]
[JsonSerializable(typeof(GitHubApiError))]
internal partial class GitHubJsonSerializerContext : JsonSerializerContext
{
}

internal sealed class GitHubApiError
{
    [JsonPropertyName("message")]
    public string? Message { get; init; }
}
