# This workflow builds and deploys the Native AOT auth host.

name: Build and deploy JitHub auth app

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: jithubauth
  AZURE_WEBAPP_PACKAGE_PATH: JitHub.Auth
  DOTNET_RUNTIME: 'linux-x64'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Install Native AOT prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --yes clang zlib1g-dev

    - name: Publish Native AOT auth app
      run: |
        dotnet publish ./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/JitHub.Auth.csproj \
          --configuration Release \
          --runtime ${{ env.DOTNET_RUNTIME }} \
          --output ./publish

    - name: Deploy to Azure Web App for Linux
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./publish
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9634DB30B22840AC94FBE0D1DB96FEAF }}
